server:
  port: 8092
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 30MB    #限制文件上传大小
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
 #fastdfs

fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:  #缩略图
    width: 60
    height: 60
  tracker-list:   #tracker地址
    - 192.168.119.130:22122
ly:
  upload:
    baseUrl: "http://image.leyou.com/"
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
