server:
  port: 8093
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.119.130:9300
  jackson:
    default-property-inclusion: non_null    #排除json为null的数据
  rabbitmq:
    host: 192.168.119.130
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
hystrix:
  command:
    default:
     execution:
        timeout:
          enabled: true
        isolation:
          thread:
          timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 300007.0.0.1



