server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api    #添加路由前缀ribbon
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false   #false不会移除前缀
  add-host-header: true
  sensitive-headers:  #覆盖敏感头信息，使cookie可以正常写入
#配置hystrix延迟时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 5000
ribbon:
  ReadTimeout: 1000    #读取时长
  ConnectionTimeout: 3500   #链接超时时长
  MaxAutoRetries: 0  #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
spring:
  application:
    name: api-gateway
ly:
  jwt:
    pubKeyPath: /Users/mundane/develop/temp/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:     #允许访问路径，允许的路径就不需要经过过滤器
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
