server:
  port: 8095
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.119.130
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.119.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.user.pojo